#!/bin/bash

# Terminal-Only Deployment Helper Script
# This script guides you through deployment with minimal browser interaction

echo "🚀 Backend Deployment - Terminal-First Approach"
echo "================================================"
echo ""
echo "Unfortunately, ALL cloud platforms (Render, Railway, Heroku, Vercel, AWS)"
echo "require ONE-TIME browser authentication for security."
echo ""
echo "However, after initial setup, everything else is TERMINAL ONLY!"
echo ""
echo "Choose your platform:"
echo "1) Render (Recommended - Easiest)"
echo "2) Railway"
echo "3) Heroku"
echo ""
read -p "Enter choice (1/2/3): " choice

case $choice in
    1)
        echo ""
        echo "📦 RENDER DEPLOYMENT"
        echo "===================="
        echo ""
        echo "STEP 1: One-time browser setup (30 seconds)"
        echo "--------------------------------------------"
        echo "Run this command:"
        echo "  open 'https://dashboard.render.com/blueprint/new?repo=https://github.com/somesh-dotcom/assured-contract-farming'"
        echo ""
        echo "Then:"
        echo "  1. Click 'Apply Blueprint' (ONE CLICK)"
        echo "  2. Wait 3-5 minutes for deployment"
        echo ""
        echo "STEP 2: Get URL (Terminal)"
        echo "---------------------------"
        echo "After deployment, come back and run:"
        echo "  ./get-render-url.sh"
        echo ""
        ;;
    2)
        echo ""
        echo "🚂 RAILWAY DEPLOYMENT"
        echo "====================="
        echo ""
        echo "STEP 1: One-time browser setup (20 seconds)"
        echo "--------------------------------------------"
        echo "Run this command:"
        echo "  open 'https://railway.com/project/d3c2ebda-1a14-4451-bddf-d79b0299f2ed'"
        echo ""
        echo "Then:"
        echo "  1. Click 'assured-contract-farming' service"
        echo "  2. Go to Variables tab"
        echo "  3. Click 'Add Reference Variable'"
        echo "  4. Select 'Postgres-IFzD' → 'DATABASE_URL'"
        echo "  5. Fix Root Directory to 'server-java' in Settings"
        echo ""
        echo "STEP 2: Deploy (Terminal)"
        echo "--------------------------"
        echo "After setup, come back and run:"
        echo "  cd server-java && railway redeploy"
        echo "  railway domain"
        echo ""
        ;;
    3)
        echo ""
        echo "🌐 HEROKU DEPLOYMENT"
        echo "===================="
        echo ""
        echo "STEP 1: One-time browser login (10 seconds)"
        echo "--------------------------------------------"
        echo "Run this command:"
        echo "  heroku login"
        echo ""
        echo "Then:"
        echo "  1. Press any key when prompted"
        echo "  2. Browser opens - click 'Login'"
        echo "  3. Come back to terminal"
        echo ""
        echo "STEP 2: Deploy (Terminal)"
        echo "--------------------------"
        echo "After login, run:"
        echo "  ./deploy-heroku.sh"
        echo ""
        ;;
    *)
        echo "Invalid choice"
        exit 1
        ;;
esac

echo ""
echo "📝 NOTE:"
echo "========="
echo "Cloud platforms require browser authentication for security."
echo "This is a ONE-TIME setup. After that, all deployments are terminal-only!"
echo ""
echo "Once you have your backend URL, I'll update your Vercel frontend automatically."
echo ""
